#!/usr/bin/env bash
# nim-code integration test suite.
#
# Wraps bench/scripts/run_suite.sh with a strict exit status so CI can gate
# on it: exit 0 if no more than MAX_FAIL tasks failed, exit 1 otherwise.
#
# Usage:
#   ./test.sh                                            # default kimi, MAX_FAIL=0
#   MODEL=meta/llama-3.3-70b-instruct ./test.sh          # different model
#   MAX_FAIL=1 ./test.sh                                 # tolerate 1 failure
#   MAX_TURNS=20 ./test.sh                               # raise the turn cap
#
# Env passed through to the runner:
#   MODEL       NIM model id (default: moonshotai/kimi-k2.6)
#   MAX_TURNS   per-task turn cap (default: 15)
#   NIM_URL     override the chat-completions endpoint (default: NVIDIA upstream)
#   NIM_TIMEOUT urlopen timeout in seconds (default: 120)
#
# Env specific to this wrapper:
#   MAX_FAIL    max FAIL+NO-SCORE tasks tolerated before this script exits 1
#               (default: 0)
set -uo pipefail
cd "$(dirname "$0")"

MODEL="${MODEL:-moonshotai/kimi-k2.6}"
MAX_TURNS="${MAX_TURNS:-15}"
MAX_FAIL="${MAX_FAIL:-0}"

if [ ! -x bench/scripts/run_suite.sh ]; then
  chmod +x bench/scripts/run_suite.sh
fi

opencode_ver="$(opencode --version 2>/dev/null || echo unknown)"
nimcode_ver="$(git -C "$(dirname "$0")" describe --tags --always 2>/dev/null || echo unknown)"

echo "=========================================="
echo " nim-code tests"
echo "=========================================="
echo " model:           $MODEL"
echo " max turns:       $MAX_TURNS"
echo " max fail:        $MAX_FAIL"
echo " opencode:        $opencode_ver"
echo " nim-code (git):  $nimcode_ver"
echo "=========================================="

MODEL="$MODEL" MAX_TURNS="$MAX_TURNS" bash bench/scripts/run_suite.sh
runner_rc=$?

# Locate the SUMMARY the runner just wrote.
SUM=$(ls -td /tmp/nim_suite_*/SUMMARY.md 2>/dev/null | head -1)
if [ -z "$SUM" ] || [ ! -f "$SUM" ]; then
  echo "FATAL: no SUMMARY.md found (runner exit=$runner_rc)" >&2
  exit 2
fi

# Stamp runtime versions into the SUMMARY (post-hoc — runner is upstream-stable).
# This is what makes a "baseline" actually mean something: each SUMMARY records
# what produced it, so future comparisons aren't ambiguous.
{
  echo
  echo "## runtime"
  echo
  echo "- opencode:       \`$opencode_ver\`"
  echo "- nim-code (git): \`$nimcode_ver\`"
  echo "- generated by:   \`./test.sh\`"
} >> "$SUM"

# Count failures + no-scores from the markdown table.
fails=$(awk -F'|' '/^\| [^|]+ \| FAIL /     {n++} END {print n+0}' "$SUM")
noscore=$(awk -F'|' '/^\| [^|]+ \| NO-SCORE / {n++} END {print n+0}' "$SUM")
total_fail=$((fails + noscore))
total=$(awk -F'|' '/^\| [0-9]/ {n++} END {print n+0}' "$SUM")
pass=$((total - total_fail))

echo
echo "=========================================="
echo " result"
echo "=========================================="
echo " summary file: $SUM"
echo " pass / total: $pass / $total"
echo " failed:       $total_fail   (allowed: $MAX_FAIL)"
echo "=========================================="

if [ "$total_fail" -gt "$MAX_FAIL" ]; then
  echo "FAIL"
  exit 1
fi
echo "PASS"
exit 0
